version: "3.8"

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_password
      - db_root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443" # had to add 8 because if run as not root: have to be port > 1024, if u type localhost by default it will be 433, now have to do: inception.42.fr:8443
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    healthcheck:
      #test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost"]
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider https://localhost:443 --no-check-certificate || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt